### ISSUE TITLE
Collection test not found

### ISSUE THREAD

**Issue by HaoWeiWang** [chaoql/rag-best-practices#3]
你好请问，为什么在开启混合搜索时，会出现raise ValueError(f"Collection {collection_name} not found")的问题？
详细错误信息如下：
Traceback (most recent call last):
  File "/hde/rag-best-practices/main.py", line 129, in <module>
    response = rag_query_engine.query(query_str)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 260, in wrapper
    result = func(*args, **kwargs)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/base/base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 260, in wrapper
    result = func(*args, **kwargs)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 189, in _query
    nodes = self.retrieve(query_bundle)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 144, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 260, in wrapper
    result = func(*args, **kwargs)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 243, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 260, in wrapper
    result = func(*args, **kwargs)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 101, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 177, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/llama_index/vector_stores/qdrant/base.py", line 726, in query
    sparse_response = self._client.search_batch(
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 288, in search_batch
    return self._client.search_batch(
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py", line 169, in search_batch
    collection = self._get_collection(collection_name)
  File "/hde/miniconda3/envs/AIHome/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py", line 161, in _get_collection
    raise ValueError(f"Collection {collection_name} not found")
ValueError: Collection test not found

**Comment by HaoWeiWang** [comment]
打扰了，找到问题了，应该是网络原因
